/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Prueb.java
 *
 * Created on 12-jun-2015, 12:00:52
 */
package GUI;

import javasamplesformifarecards.*;
import java.awt.*;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import javax.smartcardio.*;
import javax.smartcardio.ATR;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame; 
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
/**
 *
 * @author silvia
 */
public class Prueb extends javax.swing.JFrame {

    /** Creates new form Prueb */
    public Prueb() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        Boton1 = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();
        Cargar = new javax.swing.JButton();
        Cargar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 255));

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 255));
        jDesktopPane1.setForeground(new java.awt.Color(0, 0, 255));
        jDesktopPane1.setName("jDesktopPane1"); // NOI18N

        jInternalFrame1.setName("jInternalFrame1"); // NOI18N
        jInternalFrame1.setVisible(true);

        Boton1.setText("Ingresar");
        Boton1.setName("Boton1"); // NOI18N
        Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(446, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Boton1)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jInternalFrame1.setBounds(40, 10, 660, 280);
        jDesktopPane1.add(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        escritorio.setName("escritorio"); // NOI18N

        Cargar.setText("Cargar");
        Cargar.setName("Cargar"); // NOI18N
        Cargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CargarMouseClicked(evt);
            }
        });
        Cargar.setBounds(140, 0, 100, 23);
        escritorio.add(Cargar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Cargar1.setText("Cargar");
        Cargar1.setName("Cargar1"); // NOI18N
        Cargar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cargar1MouseClicked(evt);
            }
        });
        Cargar1.setBounds(250, 0, 100, 23);
        escritorio.add(Cargar1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        escritorio.setBounds(0, 0, 460, 0);
        jDesktopPane1.add(escritorio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1MouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_Boton1MouseClicked

    private void CargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CargarMouseClicked
        // TODO add your handling code here:
       // cargarImagen(escritorio,foto1);
}//GEN-LAST:event_CargarMouseClicked

    private void Cargar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cargar1MouseClicked
        // TODO add your handling code here:
       // cargarImagen(escritorio,foto2);
}//GEN-LAST:event_Cargar1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Prueb().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Cargar;
    private javax.swing.JButton Cargar1;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    // End of variables declaration//GEN-END:variables
}
