
//****************************************************************************** 
//* @file   Java_Samples_for_Mifare_CardsAboutBox.java
//* @brief  <Brief description>
//* This displays the information on about window box
//*
//* <Long description>
//*  The Information shown in the AboutBox is 
//*  Java Sample for Mifare cards
//*  Copyright (c) 2012 HID Global Corp.
//*  V1.0.0.1
//*  
//****************************************************************************** 
//* $Id$ 
//*
//* @date January 17 ,2012
//* @version 1.0.0.1
//* 
//* Copyright © 2012 HID Global Corporation.
//* All rights reserved. 
//* Use is subject to license terms
//*******************************************************************************
/*
 * Java_Samples_for_Mifare_CardsAboutBox.java
 */

package javasamplesformifarecards;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import org.jdesktop.application.Action;

public class Java_Samples_for_Mifare_CardsAboutBox extends javax.swing.JDialog 
{

    public Java_Samples_for_Mifare_CardsAboutBox(java.awt.Frame parent) {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
        setTitle("About ...");
        setBackground(new Color(255,255,240));
        //setSize(350, 120);
    }

    @Action public void closeAboutBox() {
        dispose();
//        Java_Samples_for_Mifare_CardsApp ob=new Java_Samples_for_Mifare_CardsApp();
//        ob.t.restart();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        javax.swing.JLabel appTitleLabel = new javax.swing.JLabel();
        javax.swing.JLabel appVersionLabel = new javax.swing.JLabel();
        javax.swing.JLabel appHomepageLabel = new javax.swing.JLabel();
        javax.swing.JLabel appDescLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(javasamplesformifarecards.Java_Samples_for_Mifare_CardsApp.class).getContext().getResourceMap(Java_Samples_for_Mifare_CardsAboutBox.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setAlwaysOnTop(true);
        setBackground(resourceMap.getColor("aboutBox.background")); // NOI18N
        setIconImage(null);
        setMinimumSize(new java.awt.Dimension(217, 135));
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(javasamplesformifarecards.Java_Samples_for_Mifare_CardsApp.class).getContext().getActionMap(Java_Samples_for_Mifare_CardsAboutBox.class, this);
        closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        closeButton.setText(resourceMap.getString("closeButton.text")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N

        appTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        appTitleLabel.setText(resourceMap.getString("Application.title")); // NOI18N
        appTitleLabel.setName("appTitleLabel"); // NOI18N

        appVersionLabel.setText(resourceMap.getString("Application.version")); // NOI18N
        appVersionLabel.setName("appVersionLabel"); // NOI18N

        appHomepageLabel.setForeground(resourceMap.getColor("appHomepageLabel.foreground")); // NOI18N
        appHomepageLabel.setText(resourceMap.getString("Application.homepage")); // NOI18N
        appHomepageLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        appHomepageLabel.setName("appHomepageLabel"); // NOI18N
        appHomepageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appHomepageLabelMouseClicked(evt);
            }
        });

        appDescLabel.setText(resourceMap.getString("appDescLabel.text")); // NOI18N
        appDescLabel.setName("appDescLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appTitleLabel)
                    .addComponent(appDescLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(appVersionLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(appHomepageLabel)
                        .addGap(39, 39, 39)
                        .addComponent(closeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appDescLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appVersionLabel)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appHomepageLabel)
                    .addComponent(closeButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void appHomepageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appHomepageLabelMouseClicked
        // TODO add your handling code here:
        try
        {
            final URI uri = new URI("http://www.hidglobal.com");  
            open(uri);
        }
        catch(URISyntaxException e)
        {
            
        }
        
    }//GEN-LAST:event_appHomepageLabelMouseClicked
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    // End of variables declaration//GEN-END:variables

    private void open(URI uri) {
       // throw new UnsupportedOperationException("Not yet implemented");
                
        if (Desktop.isDesktopSupported()) 
        { 
                Desktop desktop = Desktop.getDesktop(); 
                try { 
                        desktop.browse(uri); 
                } catch (IOException e) { 
                        // TODO: error handling 
                } 
        } else { 
                // TODO: error handling 
        }

        
    }
    
}
